// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI_nm1DdB4hiU9WdMNqUGyt48fBaZGt78',
    appId: '1:644739020642:web:ab653107996e2b045f9e3b',
    messagingSenderId: '644739020642',
    projectId: 'cyber-education-40597',
    authDomain: 'cyber-education-40597.firebaseapp.com',
    storageBucket: 'cyber-education-40597.firebasestorage.app',
    measurementId: 'G-ZWBVJRHQMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN0SFwotk1vZB-t8GlAjcOwqbU92uhbHs',
    appId: '1:644739020642:android:0d101fa0348d629d5f9e3b',
    messagingSenderId: '644739020642',
    projectId: 'cyber-education-40597',
    storageBucket: 'cyber-education-40597.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB518Q3BXytY7ZQDUFoUsUls_gEGX8ux1I',
    appId: '1:644739020642:ios:f138d01b22e8bc8f5f9e3b',
    messagingSenderId: '644739020642',
    projectId: 'cyber-education-40597',
    storageBucket: 'cyber-education-40597.firebasestorage.app',
    iosBundleId: 'com.example.cyberEducation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB518Q3BXytY7ZQDUFoUsUls_gEGX8ux1I',
    appId: '1:644739020642:ios:f138d01b22e8bc8f5f9e3b',
    messagingSenderId: '644739020642',
    projectId: 'cyber-education-40597',
    storageBucket: 'cyber-education-40597.firebasestorage.app',
    iosBundleId: 'com.example.cyberEducation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI_nm1DdB4hiU9WdMNqUGyt48fBaZGt78',
    appId: '1:644739020642:web:e4fe2b2e834459fc5f9e3b',
    messagingSenderId: '644739020642',
    projectId: 'cyber-education-40597',
    authDomain: 'cyber-education-40597.firebaseapp.com',
    storageBucket: 'cyber-education-40597.firebasestorage.app',
    measurementId: 'G-MDHY284WJP',
  );
}
